services:
  web:
    build: .
    image: nexa-paraguay:prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=https://qyvokpribmbrosafntqa.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_KQ-sFNr7r6AauoG0B4nyTg_vuPHmeCm
      - SUPABASE_SERVICE_ROLE_KEY=sb_secret_J7n1igQHaVSKn35OrMe93A_p-_FEBvH
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=agent-net"
      - "traefik.http.routers.nexa-paraguay.rule=Host(`nexa.paragu-ai.com`) || Host(`nexa-paraguay.paragu-ai.com`)"
      - "traefik.http.routers.nexa-paraguay.entrypoints=websecure"
      - "traefik.http.routers.nexa-paraguay.tls=true"
      - "traefik.http.routers.nexa-paraguay.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.nexa-paraguay.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.nexa-compress.compress=true"
      - "traefik.http.routers.nexa-paraguay.middlewares=nexa-compress"
    networks:
      - agent-net

networks:
  agent-net:
    external: true
